name: "CommandCrawlerAssist Addon"
description: "Sends Home Assistant states to CommandCrawler"
version: "0.1.43"
slug: "commandcrawler_assist"
homeassistant_api: true
supervisor_api: true
#hassio_role: homeassistant
host_network: true
full_access: true
privileged:
  - SYS_ADMIN
apparmor: false
map:
  - "share:rw"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  assist_token: ""
  external_server_url: "https://rs-command-crawler.azurewebsites.net"
  polling_interval: 10 
  timeout: 30
schema:
  assist_token: str
  external_server_url: str
  polling_interval: int(10,3600)
  timeout: int(5,300)