name: "CommandCrawlerAssist Addon"
description: "Sends Home Assistant states to CommandCrawler"
version: "0.1.25"
slug: "commandcrawler_assist"
homeassistant_api: true
#hassio_api: true
#hassio_role: homeassistant
#network: host
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  hass_token: ""
  assist_token: ""
  external_server_url: "https://rs-command-crawler.azurewebsites.net"
  polling_interval: 60
  timeout: 30
schema:
  hass_token: str
  assist_token: str
  external_server_url: str
  polling_interval: int(10,3600)
  timeout: int(5,300)